#create a dynamic storage definition
#Platinum will be for a top tier class of storage, better than gold 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  #ensure the name 'gold' matches in the PVC definition
  name: platinum
#AWS EFS: efs.csi.aws.com
#AWS: EBS: ebs.csi.aws.com
#GCP: kubernetes.io/gce-pd
provisioner: kubernetes.io/gce-pd
parameters:
  #pd-ssd
  #pd-standard (HDD)
  type: pd-ssd
  #none
  #regional-pd
  replication-type: regional-pd