#kubectl create -f pvc-definition.yaml
#kubectl get persistentcolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi