#create a dynamic storage definition 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  #ensure the name 'google-storage' matches in the PVC definition
  name: google-storage
#AWS EFS: efs.csi.aws.com
#AWS: EBS: ebs.csi.aws.com
#GCP: kubernetes.io/gce-pd
provisioner: kubernetes.io/gce-pd
parameters:
  #pd-ssd
  #pd-standard (HDD)
  type: pd-standard
  #none
  #regional-pd
  replication-type: regional-pd