#setting Security Contexts at the container level
apiVersion: v1
kind: pod
metadata:
  name: web-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "3600"]
      securityContext:
        runAsUser: 1000
        capabilities:
          #using the add here will append the container user the ability to have MAC_ADMIN priv as an example
          #this could also be for removing priv as well to lock down the container permissions even more
          add: ["MAC_ADMIN"]