#Creates a Persistent Volume (pv) Administrator cluster role and corresponding cluster rollbinding
#Username is intentionally left as a varible that could be defined at a later date or placed within a user file elsewhere for easier management
#For example; within the file ./clusterrole with the value of username1 elsewhere in this repo or defined locally to override any file changes
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-admin
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "watch", "list", "create", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {$username1.clusterole}-admin
subjects:
- kind: User
  name: {$username1.clusterole}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: storage-admin
  apiGroup: rbac.authorization.k8s.io